version: 2
sources:
  - name: raw_data
    description: "Raw data sources for NYC taxi data"
    tables:
      - name: yellow_tripdata
        meta:
          external_location: "read_parquet('data/yellow/*.parquet')"
      - name: green_tripdata
        meta:
          external_location: "read_parquet('data/green/*.parquet')"
      - name: fhv_tripdata
        meta:
          external_location: "read_parquet('data/fhv/*.parquet')"
